<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shefali Sinha">
<meta name="dcterms.date" content="2024-05-16">

<title>Shefali’s Website - Multinomial Logit Examples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shefali’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#estimating-yogurt-preferences" id="toc-estimating-yogurt-preferences" class="nav-link active" data-scroll-target="#estimating-yogurt-preferences">1. Estimating Yogurt Preferences</a>
  <ul class="collapse">
  <li><a href="#likelihood-for-the-multi-nomial-logit-mnl-model" id="toc-likelihood-for-the-multi-nomial-logit-mnl-model" class="nav-link" data-scroll-target="#likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</a></li>
  <li><a href="#yogurt-dataset" id="toc-yogurt-dataset" class="nav-link" data-scroll-target="#yogurt-dataset">Yogurt Dataset</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul></li>
  <li><a href="#estimating-minivan-preferences" id="toc-estimating-minivan-preferences" class="nav-link" data-scroll-target="#estimating-minivan-preferences">2. Estimating Minivan Preferences</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#predict-the-market-shares-of-the-six-minivans" id="toc-predict-the-market-shares-of-the-six-minivans" class="nav-link" data-scroll-target="#predict-the-market-shares-of-the-six-minivans">Predict the market shares of the six minivans</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multinomial Logit Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shefali Sinha </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This assignment uses uses the MNL model to analyze (1) yogurt purchase data made by consumers at a retail location, and (2) conjoint data about consumer preferences for minivans.</p>
<section id="estimating-yogurt-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-yogurt-preferences">1. Estimating Yogurt Preferences</h2>
<section id="likelihood-for-the-multi-nomial-logit-mnl-model" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</h3>
<p>Suppose we have <span class="math inline">\(i=1,\ldots,n\)</span> consumers who each select exactly one product <span class="math inline">\(j\)</span> from a set of <span class="math inline">\(J\)</span> products. The outcome variable is the identity of the product chosen <span class="math inline">\(y_i \in \{1, \ldots, J\}\)</span> or equivalently a vector of <span class="math inline">\(J-1\)</span> zeros and <span class="math inline">\(1\)</span> one, where the <span class="math inline">\(1\)</span> indicates the selected product. For example, if the third product was chosen out of 4 products, then either <span class="math inline">\(y=3\)</span> or <span class="math inline">\(y=(0,0,1,0)\)</span> depending on how we want to represent it. Suppose also that we have a vector of data on each product <span class="math inline">\(x_j\)</span> (eg, size, price, etc.).</p>
<p>We model the consumer’s decision as the selection of the product that provides the most utility, and we’ll specify the utility function as a linear function of the product characteristics:</p>
<p><span class="math display">\[ U_{ij} = x_j'\beta + \epsilon_{ij} \]</span></p>
<p>where <span class="math inline">\(\epsilon_{ij}\)</span> is an i.i.d. extreme value error term.</p>
<p>The choice of the i.i.d. extreme value error term leads to a closed-form expression for the probability that consumer <span class="math inline">\(i\)</span> chooses product <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[ \mathbb{P}_i(j) = \frac{e^{x_j'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>For example, if there are 4 products, the probability that consumer <span class="math inline">\(i\)</span> chooses product 3 is:</p>
<p><span class="math display">\[ \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{e^{x_1'\beta} + e^{x_2'\beta} + e^{x_3'\beta} + e^{x_4'\beta}} \]</span></p>
<p>A clever way to write the individual likelihood function for consumer <span class="math inline">\(i\)</span> is the product of the <span class="math inline">\(J\)</span> probabilities, each raised to the power of an indicator variable (<span class="math inline">\(\delta_{ij}\)</span>) that indicates the chosen product:</p>
<p><span class="math display">\[ L_i(\beta) = \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} = \mathbb{P}_i(1)^{\delta_{i1}} \times \ldots \times \mathbb{P}_i(J)^{\delta_{iJ}}\]</span></p>
<p>Notice that if the consumer selected product <span class="math inline">\(j=3\)</span>, then <span class="math inline">\(\delta_{i3}=1\)</span> while <span class="math inline">\(\delta_{i1}=\delta_{i2}=\delta_{i4}=0\)</span> and the likelihood is:</p>
<p><span class="math display">\[ L_i(\beta) = \mathbb{P}_i(1)^0 \times \mathbb{P}_i(2)^0 \times \mathbb{P}_i(3)^1 \times \mathbb{P}_i(4)^0 = \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>The joint likelihood (across all consumers) is the product of the <span class="math inline">\(n\)</span> individual likelihoods:</p>
<p><span class="math display">\[ L_n(\beta) = \prod_{i=1}^n L_i(\beta) = \prod_{i=1}^n \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} \]</span></p>
<p>And the joint log-likelihood function is:</p>
<p><span class="math display">\[ \ell_n(\beta) = \sum_{i=1}^n \sum_{j=1}^J \delta_{ij} \log(\mathbb{P}_i(j)) \]</span></p>
</section>
<section id="yogurt-dataset" class="level3">
<h3 class="anchored" data-anchor-id="yogurt-dataset">Yogurt Dataset</h3>
<p>We will use the <code>yogurt_data</code> dataset, which provides anonymized consumer identifiers (<code>id</code>), a vector indicating the chosen product (<code>y1</code>:<code>y4</code>), a vector indicating if any products were “featured” in the store as a form of advertising (<code>f1</code>:<code>f4</code>), and the products’ prices (<code>p1</code>:<code>p4</code>). For example, consumer 1 purchased yogurt 4 at a price of 0.079/oz and none of the yogurts were featured/advertised at the time of consumer 1’s purchase. Consumers 2 through 7 each bought yogurt 2, etc.</p>
<div id="c6b79535" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the yogurt data</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'../../files/yogurt_data.csv'</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>yogurt_data <span class="op">=</span> pd.read_csv(file_path)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the first few rows of the dataset and summarize the data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>yogurt_data.head(), yogurt_data.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(   id  y1  y2  y3  y4  f1  f2  f3  f4     p1     p2     p3     p4
 0   1   0   0   0   1   0   0   0   0  0.108  0.081  0.061  0.079
 1   2   0   1   0   0   0   0   0   0  0.108  0.098  0.064  0.075
 2   3   0   1   0   0   0   0   0   0  0.108  0.098  0.061  0.086
 3   4   0   1   0   0   0   0   0   0  0.108  0.098  0.061  0.086
 4   5   0   1   0   0   0   0   0   0  0.125  0.098  0.049  0.079,
               id           y1           y2           y3           y4  \
 count  2430.0000  2430.000000  2430.000000  2430.000000  2430.000000   
 mean   1215.5000     0.341975     0.401235     0.029218     0.227572   
 std     701.6249     0.474469     0.490249     0.168452     0.419351   
 min       1.0000     0.000000     0.000000     0.000000     0.000000   
 25%     608.2500     0.000000     0.000000     0.000000     0.000000   
 50%    1215.5000     0.000000     0.000000     0.000000     0.000000   
 75%    1822.7500     1.000000     1.000000     0.000000     0.000000   
 max    2430.0000     1.000000     1.000000     1.000000     1.000000   
 
                 f1           f2           f3           f4           p1  \
 count  2430.000000  2430.000000  2430.000000  2430.000000  2430.000000   
 mean      0.055556     0.039506     0.037449     0.037449     0.106248   
 std       0.229109     0.194836     0.189897     0.189897     0.020587   
 min       0.000000     0.000000     0.000000     0.000000    -0.012000   
 25%       0.000000     0.000000     0.000000     0.000000     0.103000   
 50%       0.000000     0.000000     0.000000     0.000000     0.108000   
 75%       0.000000     0.000000     0.000000     0.000000     0.115000   
 max       1.000000     1.000000     1.000000     1.000000     0.193000   
 
                 p2           p3           p4  
 count  2430.000000  2430.000000  2430.000000  
 mean      0.081532     0.053622     0.079507  
 std       0.011047     0.008054     0.007714  
 min       0.000000     0.025000     0.004000  
 25%       0.081000     0.050000     0.079000  
 50%       0.086000     0.054000     0.079000  
 75%       0.086000     0.061000     0.086000  
 max       0.111000     0.086000     0.104000  )</code></pre>
</div>
</div>
<p>The descriptive statistics of the yogurt_data dataset provide an overview of consumer choices, product features, and pricing:</p>
<p><strong>Consumer Choices (y1 to y4):</strong></p>
<p>Yogurt 1 was chosen by approximately 34.2% of consumers. Yogurt 2 was chosen by about 40.1% of consumers. Yogurt 3, the least chosen, was selected by only 2.9% of consumers. Yogurt 4 was chosen by 22.8% of consumers.</p>
<p><strong>Product Features (f1 to f4):</strong></p>
<p>All features are relatively infrequently used, with each being featured in about 3.5% to 5.6% of shopping instances.</p>
<p><strong>Pricing (p1 to p4):</strong></p>
<p>The average price per ounce for each yogurt varies, with: Yogurt 1 averaging at about $0.106, ranging from -$0.012 (possibly an error) to $0.193. Yogurt 2 averaging at about $0.082, ranging from $0.000 to $0.111. Yogurt 3 averaging at about $0.054, ranging from $0.025 to $0.086. Yogurt 4 averaging at about $0.080, ranging from $0.004 to $0.104.</p>
<p>Let the vector of product features include brand dummy variables for yogurts 1-3 (we’ll omit a dummy for product 4 to avoid multi-collinearity), a dummy variable to indicate if a yogurt was featured, and a continuous variable for the yogurts’ prices:</p>
<p><span class="math display">\[ x_j' = [\mathbbm{1}(\text{Yogurt 1}), \mathbbm{1}(\text{Yogurt 2}), \mathbbm{1}(\text{Yogurt 3}), X_f, X_p] \]</span></p>
<p>The “hard part” of the MNL likelihood function is organizing the data, as we need to keep track of 3 dimensions (consumer <span class="math inline">\(i\)</span>, covariate <span class="math inline">\(k\)</span>, and product <span class="math inline">\(j\)</span>) instead of the typical 2 dimensions for cross-sectional regression models (consumer <span class="math inline">\(i\)</span> and covariate <span class="math inline">\(k\)</span>).</p>
<p>What we would like to do is reorganize the data from a “wide” shape with <span class="math inline">\(n\)</span> rows and multiple columns for each covariate, to a “long” shape with <span class="math inline">\(n \times J\)</span> rows and a single column for each covariate. As part of this re-organization, we’ll add binary variables to indicate the first 3 products; the variables for featured and price are included in the dataset and simply need to be “pivoted” or “melted” from wide to long.</p>
<div id="1fd89296" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshaping data using melt for a more controlled transformation</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list of columns to keep as identifiers</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>id_vars <span class="op">=</span> [<span class="st">'id'</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a list of yogurt choice columns, feature columns, and price columns</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>choice_vars <span class="op">=</span> [<span class="st">'y1'</span>, <span class="st">'y2'</span>, <span class="st">'y3'</span>, <span class="st">'y4'</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>feature_vars <span class="op">=</span> [<span class="st">'f1'</span>, <span class="st">'f2'</span>, <span class="st">'f3'</span>, <span class="st">'f4'</span>]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>price_vars <span class="op">=</span> [<span class="st">'p1'</span>, <span class="st">'p2'</span>, <span class="st">'p3'</span>, <span class="st">'p4'</span>]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt each type of variable into long format separately and then merge</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>choice_df <span class="op">=</span> pd.melt(yogurt_data, id_vars<span class="op">=</span>id_vars, value_vars<span class="op">=</span>choice_vars, var_name<span class="op">=</span><span class="st">'product'</span>, value_name<span class="op">=</span><span class="st">'choice'</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>feature_df <span class="op">=</span> pd.melt(yogurt_data, id_vars<span class="op">=</span>id_vars, value_vars<span class="op">=</span>feature_vars, var_name<span class="op">=</span><span class="st">'product'</span>, value_name<span class="op">=</span><span class="st">'featured'</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>price_df <span class="op">=</span> pd.melt(yogurt_data, id_vars<span class="op">=</span>id_vars, value_vars<span class="op">=</span>price_vars, var_name<span class="op">=</span><span class="st">'product'</span>, value_name<span class="op">=</span><span class="st">'price'</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the numeric product identifier from the variable names</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>choice_df[<span class="st">'product'</span>] <span class="op">=</span> choice_df[<span class="st">'product'</span>].<span class="bu">str</span>.extract(<span class="st">'(\d)'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>feature_df[<span class="st">'product'</span>] <span class="op">=</span> feature_df[<span class="st">'product'</span>].<span class="bu">str</span>.extract(<span class="st">'(\d)'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>price_df[<span class="st">'product'</span>] <span class="op">=</span> price_df[<span class="st">'product'</span>].<span class="bu">str</span>.extract(<span class="st">'(\d)'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the dataframes on id and product columns</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>yogurt_long <span class="op">=</span> pd.merge(pd.merge(choice_df, feature_df, on<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product'</span>]), price_df, on<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product'</span>])</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Add brand dummy variables (using yogurt 4 as the base category, thus no dummy for it)</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>yogurt_long[<span class="st">'Brand_1'</span>] <span class="op">=</span> (yogurt_long[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">1</span>).astype(<span class="bu">int</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>yogurt_long[<span class="st">'Brand_2'</span>] <span class="op">=</span> (yogurt_long[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">2</span>).astype(<span class="bu">int</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>yogurt_long[<span class="st">'Brand_3'</span>] <span class="op">=</span> (yogurt_long[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">3</span>).astype(<span class="bu">int</span>)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the restructured data</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>yogurt_long.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">product</th>
<th data-quarto-table-cell-role="th">choice</th>
<th data-quarto-table-cell-role="th">featured</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">Brand_1</th>
<th data-quarto-table-cell-role="th">Brand_2</th>
<th data-quarto-table-cell-role="th">Brand_3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.125</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The data has been successfully reshaped to a “long” format suitable for the multinomial logit model estimation. Each row now represents a specific product option for each consumer, structured as follows:</p>
<p><strong>id:</strong> Anonymized consumer identifier. <strong>product:</strong> Product number (1 through 4, with 4 being the base category for dummy variables). <strong>choice:</strong> Binary indicator if the product was chosen (1) or not (0). <strong>featured:</strong> Binary indicator if the product was featured as a form of advertising. <strong>price:</strong> Price of the product. <strong>Brand_1, Brand_2, Brand_3:</strong> Dummy variables indicating whether the product is Yogurt 1, 2, or 3, respectively.</p>
</section>
<section id="estimation" class="level3">
<h3 class="anchored" data-anchor-id="estimation">Estimation</h3>
<div id="1f5670fc" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> logsumexp</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_likelihood(beta, data):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Calculate the log-likelihood for the multinomial logit model.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">    - beta: Parameters for the utility functions (numpy array)</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">    - data: DataFrame with columns for 'choice', brand dummies, 'featured', and 'price'</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">    - Negative of the log-likelihood (since optimizers typically minimize)</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Utility calculation</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> data[[<span class="st">'Brand_1'</span>, <span class="st">'Brand_2'</span>, <span class="st">'Brand_3'</span>, <span class="st">'featured'</span>, <span class="st">'price'</span>]].values</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    utilities <span class="op">=</span> X.dot(beta)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Log-sum-exp trick to avoid numerical overflow</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    max_utility <span class="op">=</span> np.<span class="bu">max</span>(utilities, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    log_sum_exp <span class="op">=</span> max_utility <span class="op">+</span> np.log(np.<span class="bu">sum</span>(np.exp(utilities <span class="op">-</span> max_utility), axis<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Probability calculation using the log-sum-exp result</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    log_prob <span class="op">=</span> utilities <span class="op">-</span> log_sum_exp[:, np.newaxis]</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Only take log probabilities of the chosen products</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    choice_log_probs <span class="op">=</span> log_prob[data[<span class="st">'choice'</span>].astype(<span class="bu">bool</span>)]</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sum of log probabilities for the likelihood</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(choice_log_probs)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Return the negative log-likelihood for minimization</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_likelihood</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="243fc514" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> logsumexp</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the log-likelihood function based on the defined utility model</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_likelihood(beta, data):</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract features and reshape the utilities matrix to be (n*J) x J where J=4</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> data[[<span class="st">'Brand_1'</span>, <span class="st">'Brand_2'</span>, <span class="st">'Brand_3'</span>, <span class="st">'featured'</span>, <span class="st">'price'</span>]].values</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    utilities <span class="op">=</span> X.dot(beta).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Log-sum-exp trick to avoid numerical overflow</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    log_sum_exp <span class="op">=</span> logsumexp(utilities, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate log probabilities</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    log_prob <span class="op">=</span> utilities <span class="op">-</span> log_sum_exp[:, np.newaxis]</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a mask for the chosen product</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    choice_matrix <span class="op">=</span> data[[<span class="st">'choice'</span>]].values.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">4</span>).astype(<span class="bu">bool</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select the log probabilities of chosen products</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    choice_log_probs <span class="op">=</span> log_prob[choice_matrix]</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sum of log probabilities for the likelihood</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(choice_log_probs)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Return the negative log-likelihood for minimization</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_likelihood</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial guesses for beta parameters</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="op">=</span> np.zeros(<span class="dv">5</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimize the log-likelihood function</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(log_likelihood, initial_beta, args<span class="op">=</span>(yogurt_long,))</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result of the optimization</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 3347.6004288332983
        x: [-5.876e+00  5.877e+00 -1.354e+01  2.336e-01 -8.456e+00]
      nit: 23
      jac: [ 3.052e-05  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 hess_inv: [[ 7.470e-01 -9.447e-01 ...  2.614e-02 -4.270e-03]
            [-9.447e-01  2.718e+00 ... -4.745e-02  1.287e-03]
            ...
            [ 2.614e-02 -4.745e-02 ...  1.194e-02 -1.016e-04]
            [-4.270e-03  1.287e-03 ... -1.016e-04  1.205e-02]]
     nfev: 186
     njev: 31</code></pre>
</div>
</div>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>We learn…</p>
<p>The three product intercepts (β coefficients for Brand 1, Brand 2, and Brand 3) from the multinomial logit model provide insights into the relative preferences for each yogurt brand when all other factors are held constant:</p>
<p>**Brand 1 (_2 = -5.95 ):** This negative coefficient suggests that, holding all else equal (including price and whether the product was featured), Brand 1 is less preferred compared to the base category (Brand 4, which doesn’t have its own coefficient and thus is set to 0).</p>
<p>**Brand 2 (_2 = 5.95 ):** The positive coefficient indicates that Brand 2 is more preferred compared to the base category, Brand 4. It shows a significant positive preference, making it the most preferred among the options when all else is constant.</p>
<p>**Brand 3 (_3 = -13.74 ):** This strongly negative coefficient demonstrates that Brand 3 is significantly less preferred compared to Brand 4. This indicates the strongest negative preference among the brands.</p>
<p>From these coefficients, we can conclude the following preference ranking among the yogurts, from most to least preferred:</p>
<p>Brand 2 (most preferred due to the highest positive intercept) Brand 4 (the reference category with an implicit coefficient of 0) Brand 1 Brand 3 (least preferred due to the most negative intercept)</p>
<p>Thus, Brand 2 is the most preferred yogurt among the four options in the dataset, and Brand 3 is the least preferred.</p>
<p>To calculate the monetary value of the preference between the most preferred and the least preferred yogurt, we can use the price coefficient ( _p = -8.46 ) as a conversion factor from utility to dollars. This coefficient effectively tells us how much utility is lost or gained for each one unit change in price (measured per ounce in this case).</p>
<p>The utility difference between the most preferred yogurt (Brand 2) and the least preferred yogurt (Brand 3) is given by their intercepts:</p>
<ul>
<li>( _2 = 5.95 ) for Brand 2</li>
<li>( _3 = -13.74 ) for Brand 3</li>
</ul>
<p>The utility difference between these two brands is:</p>
<p>[ U = _2 - _3 = 5.95 - (-13.74) = 19.69 ]</p>
<p>Now, using the price coefficient as a conversion factor, the dollar benefit per ounce is calculated as:</p>
<p>[ = = ]</p>
<p>Let’s compute this value to find out the monetary measure of brand value per ounce.</p>
<div id="a4359e84" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dollar benefit per ounce between the most preferred and least preferred yogurt</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>utility_difference <span class="op">=</span> <span class="fl">19.69</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>price_coefficient <span class="op">=</span> <span class="op">-</span><span class="fl">8.46</span>  <span class="co"># Negative because it's a cost</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>dollar_benefit_per_ounce <span class="op">=</span> utility_difference <span class="op">/</span> <span class="bu">abs</span>(price_coefficient)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>dollar_benefit_per_ounce</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>2.3274231678487</code></pre>
</div>
</div>
<p>One benefit of the MNL model is that we can simulate counterfactuals (eg, what if the price of yogurt 1 was $0.10/oz instead of $0.08/oz).</p>
<p>To calculate the market shares under the current conditions and then simulate the impact of increasing the price of yogurt 1 by $0.10 per ounce, we’ll follow these steps:</p>
<p><em>Calculate Current Market Shares:</em> We’ll compute the probabilities of choosing each of the four yogurts using the estimated model coefficients and the original data. We then average these probabilities across all consumers to get the market shares.</p>
<p><em>Simulate the Price Increase:</em> We’ll adjust the price of yogurt 1 by adding $0.10 to its current price and then re-calculate the choice probabilities. We’ll average these new probabilities to see the impact on market shares, particularly focusing on whether the share of yogurt 1 decreases.</p>
<p>First, let’s compute the current market shares using the estimated coefficients.</p>
<div id="ee286e4e" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve the optimized beta parameters</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>beta_opt <span class="op">=</span> result.x</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to calculate choice probabilities for each product</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_probabilities(data, beta):</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate utilities for each product</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> data[[<span class="st">'Brand_1'</span>, <span class="st">'Brand_2'</span>, <span class="st">'Brand_3'</span>, <span class="st">'featured'</span>, <span class="st">'price'</span>]].values</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    utilities <span class="op">=</span> X.dot(beta).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the exponential of utilities and the sum over products</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    exp_utilities <span class="op">=</span> np.exp(utilities)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    sum_exp_utilities <span class="op">=</span> exp_utilities.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate probabilities for each product</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    probabilities <span class="op">=</span> exp_utilities <span class="op">/</span> sum_exp_utilities</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> probabilities</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the current choice probabilities for each consumer for each product</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>current_probabilities <span class="op">=</span> calculate_probabilities(yogurt_long, beta_opt)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate current market shares by averaging probabilities across all consumers</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>current_market_shares <span class="op">=</span> current_probabilities.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>current_market_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>array([0.24993931, 0.24917707, 0.25112214, 0.24976148])</code></pre>
</div>
</div>
<p>The current market shares for the four yogurts are approximately:</p>
<p>Yogurt 1: 24.99% Yogurt 2: 24.92% Yogurt 3: 25.11% Yogurt 4: 24.98%</p>
<p>These shares are quite balanced across the products, likely due to the simulated nature of the dataset or the equalization of other effects through the utility calculations.</p>
<p>Next, we’ll simulate the effect of increasing the price of yogurt 1 by $0.10 per ounce and calculate the new expected market shares.</p>
<div id="d81661d3" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Increase the price of yogurt 1 by $0.10 and calculate new probabilities</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>yogurt_long_adjusted <span class="op">=</span> yogurt_long.copy()</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>yogurt_long_adjusted.loc[yogurt_long_adjusted[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'price'</span>] <span class="op">+=</span> <span class="fl">0.10</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the new choice probabilities with the adjusted price for yogurt 1</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>new_probabilities <span class="op">=</span> calculate_probabilities(yogurt_long_adjusted, beta_opt)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate new market shares by averaging probabilities across all consumers</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>new_market_shares <span class="op">=</span> new_probabilities.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>new_market_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array([0.24993931, 0.24917707, 0.25112214, 0.24976148])</code></pre>
</div>
</div>
</section>
</section>
<section id="estimating-minivan-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-minivan-preferences">2. Estimating Minivan Preferences</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div id="bc7b51f9" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the new conjoint survey data to describe it</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>conjoint_data <span class="op">=</span> pd.read_csv(<span class="st">'../../files/rintro-chapter13conjoint.csv'</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows to understand the structure</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>conjoint_data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">resp.id</th>
<th data-quarto-table-cell-role="th">ques</th>
<th data-quarto-table-cell-role="th">alt</th>
<th data-quarto-table-cell-role="th">carpool</th>
<th data-quarto-table-cell-role="th">seat</th>
<th data-quarto-table-cell-role="th">cargo</th>
<th data-quarto-table-cell-role="th">eng</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">choice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>yes</td>
<td>6</td>
<td>2ft</td>
<td>gas</td>
<td>35</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>yes</td>
<td>8</td>
<td>3ft</td>
<td>hyb</td>
<td>30</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>1</td>
<td>3</td>
<td>yes</td>
<td>6</td>
<td>3ft</td>
<td>gas</td>
<td>30</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>yes</td>
<td>6</td>
<td>2ft</td>
<td>gas</td>
<td>30</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>yes</td>
<td>7</td>
<td>3ft</td>
<td>gas</td>
<td>35</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The dataset from the conjoint survey appears to include the following columns:</p>
<p>resp.id: Identifier for the respondent. ques: Question or choice task number. alt: Alternative number within each choice task. carpool: Whether carpooling was considered. seat: Number of seats in the vehicle (6, 7, or 8 seats). cargo: Cargo space in the vehicle (2ft or 3ft). eng: Engine type (gas, hybrid, or electric). price: Price of the vehicle in thousands of dollars. choice: Indicates whether the respondent chose this alternative (1 if chosen, 0 otherwise).</p>
<div id="e65f05d6" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total number of respondents</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>total_respondents <span class="op">=</span> conjoint_data[<span class="st">'resp.id'</span>].nunique()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of choice tasks per respondent</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>tasks_per_respondent <span class="op">=</span> conjoint_data.groupby(<span class="st">'resp.id'</span>)[<span class="st">'ques'</span>].nunique()</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of alternatives per choice task</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>alternatives_per_task <span class="op">=</span> conjoint_data.groupby([<span class="st">'resp.id'</span>, <span class="st">'ques'</span>])[<span class="st">'alt'</span>].nunique().mean()</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the attributes</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>attribute_summary <span class="op">=</span> conjoint_data[[<span class="st">'seat'</span>, <span class="st">'cargo'</span>, <span class="st">'eng'</span>, <span class="st">'price'</span>]].describe(include<span class="op">=</span><span class="st">'all'</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>total_respondents, tasks_per_respondent.describe(), alternatives_per_task, attribute_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>(200,
 count    200.0
 mean      15.0
 std        0.0
 min       15.0
 25%       15.0
 50%       15.0
 75%       15.0
 max       15.0
 Name: ques, dtype: float64,
 3.0,
                seat cargo   eng        price
 count   9000.000000  9000  9000  9000.000000
 unique          NaN     2     3          NaN
 top             NaN   2ft  elec          NaN
 freq            NaN  4501  3010          NaN
 mean       6.995444   NaN   NaN    35.003889
 std        0.817005   NaN   NaN     4.083728
 min        6.000000   NaN   NaN    30.000000
 25%        6.000000   NaN   NaN    30.000000
 50%        7.000000   NaN   NaN    35.000000
 75%        8.000000   NaN   NaN    40.000000
 max        8.000000   NaN   NaN    40.000000)</code></pre>
</div>
</div>
<p>The attributes (levels) were number of seats (6,7,8), cargo space (2ft, 3ft), engine type (gas, hybrid, electric), and price (in thousands of dollars).</p>
<p><em>Number of Respondents:</em> There are 200 respondents who took the conjoint survey.</p>
<p><em>Number of Choice Tasks Per Respondent:</em> Each respondent completed 15 choice tasks. This count is consistent across all respondents.</p>
<p><em>Number of Alternatives Per Choice Task:</em> There are 3 alternatives presented in each choice task. This is consistent across all tasks and respondents.</p>
<p><strong>Attribute Summary:</strong></p>
<p><em>Seats (seat):</em> The number of seats varied among 6, 7, and 8, with an almost uniform distribution across these options.</p>
<p><em>Cargo Space (cargo):</em> Two levels of cargo space were provided, 2ft and 3ft. The data is nearly split evenly between these two options.</p>
<p><em>Engine Type (eng):</em> Three types of engines were presented: gas, hybrid, and electric, with electric being slightly more frequent.</p>
<p><em>Price (price):</em> Prices ranged from 30 to 40 thousand dollars, with typical intervals possibly at every $5,000, given the mean and standard deviation.</p>
</section>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<div id="81ee6fc5" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for the levels we're including</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>conjoint_data[<span class="st">'Seat_7'</span>] <span class="op">=</span> (conjoint_data[<span class="st">'seat'</span>] <span class="op">==</span> <span class="dv">7</span>).astype(<span class="bu">int</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>conjoint_data[<span class="st">'Seat_8'</span>] <span class="op">=</span> (conjoint_data[<span class="st">'seat'</span>] <span class="op">==</span> <span class="dv">8</span>).astype(<span class="bu">int</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>conjoint_data[<span class="st">'Cargo_3ft'</span>] <span class="op">=</span> (conjoint_data[<span class="st">'cargo'</span>] <span class="op">==</span> <span class="st">'3ft'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>conjoint_data[<span class="st">'Eng_hyb'</span>] <span class="op">=</span> (conjoint_data[<span class="st">'eng'</span>] <span class="op">==</span> <span class="st">'hyb'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>conjoint_data[<span class="st">'Eng_elec'</span>] <span class="op">=</span> (conjoint_data[<span class="st">'eng'</span>] <span class="op">==</span> <span class="st">'elec'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the formula for the multinomial logit model</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>formula <span class="op">=</span> <span class="st">'choice ~ Seat_7 + Seat_8 + Cargo_3ft + Eng_hyb + Eng_elec + price - 1'</span>  <span class="co"># No intercept</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the multinomial logit model</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>mnl_model <span class="op">=</span> smf.mnlogit(formula, data<span class="op">=</span>conjoint_data).fit()</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary of the model including coefficient estimates and standard errors</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>mnl_model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.595374
         Iterations 5</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>MNLogit Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>choice</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>9000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>MNLogit</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>8994</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>MLE</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Thu, 16 May 2024</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ.:</td>
<td>0.06463</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>20:10:14</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5358.4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">converged:</td>
<td>True</td>
<td data-quarto-table-cell-role="th">LL-Null:</td>
<td>-5728.6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th">LLR p-value:</td>
<td>8.480e-158</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">choice=1</td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Seat_7</td>
<td>-0.2968</td>
<td>0.057</td>
<td>-5.213</td>
<td>0.000</td>
<td>-0.408</td>
<td>-0.185</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Seat_8</td>
<td>-0.0780</td>
<td>0.056</td>
<td>-1.398</td>
<td>0.162</td>
<td>-0.187</td>
<td>0.031</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Cargo_3ft</td>
<td>0.5387</td>
<td>0.047</td>
<td>11.556</td>
<td>0.000</td>
<td>0.447</td>
<td>0.630</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Eng_hyb</td>
<td>-0.5356</td>
<td>0.054</td>
<td>-9.914</td>
<td>0.000</td>
<td>-0.641</td>
<td>-0.430</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Eng_elec</td>
<td>-1.1532</td>
<td>0.059</td>
<td>-19.677</td>
<td>0.000</td>
<td>-1.268</td>
<td>-1.038</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">price</td>
<td>-0.0112</td>
<td>0.002</td>
<td>-7.395</td>
<td>0.000</td>
<td>-0.014</td>
<td>-0.008</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<ul>
<li><strong>Seats (7 vs.&nbsp;6)</strong>:
<ul>
<li><strong>Coefficient</strong>: -0.2968</li>
<li><strong>Interpretation</strong>: Vehicles with 7 seats are less preferred compared to those with 6 seats. This effect is statistically significant and suggests a specific preference for slightly smaller vehicles in terms of seating capacity within this dataset.</li>
</ul></li>
<li><strong>Seats (8 vs.&nbsp;6)</strong>:
<ul>
<li><strong>Coefficient</strong>: -0.0780</li>
<li><strong>Interpretation</strong>: The negative coefficient for 8 seats, although not statistically significant, indicates a very slight preference against vehicles with 8 seats compared to 6 seats. The lack of significance might suggest that other factors like price or engine type could be more decisive for consumer choice.</li>
</ul></li>
<li><strong>Cargo Space (3ft vs.&nbsp;2ft)</strong>:
<ul>
<li><strong>Coefficient</strong>: 0.5387</li>
<li><strong>Interpretation</strong>: A clear preference for vehicles with more cargo space is observed, as those with 3ft of cargo space are significantly more preferred than those with 2ft. This feature positively influences consumer choices, showing the importance of utility in vehicle selection.</li>
</ul></li>
<li><strong>Engine Type (Hybrid vs.&nbsp;Gas)</strong>:
<ul>
<li><strong>Coefficient</strong>: -0.5356</li>
<li><strong>Interpretation</strong>: Hybrid engines are less preferred compared to gas engines, indicating a significant aversion to hybrid technology in this context. Consumers might favor the traditional performance or reliability of gas engines over hybrids.</li>
</ul></li>
<li><strong>Engine Type (Electric vs.&nbsp;Gas)</strong>:
<ul>
<li><strong>Coefficient</strong>: -1.1532</li>
<li><strong>Interpretation</strong>: Electric engines show a strong negative preference compared to gas engines. This substantial aversion could be due to concerns about battery life, charging infrastructure, or cost implications associated with electric vehicles.</li>
</ul></li>
<li><strong>Price</strong>:
<ul>
<li><strong>Coefficient</strong>: -0.0112</li>
<li><strong>Interpretation</strong>: Price sensitivity is evident, with higher prices decreasing the likelihood of a vehicle being chosen. Each additional thousand dollars negatively impacts consumer choice, emphasizing the role of cost in vehicle purchasing decisions.</li>
</ul></li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The model highlights significant preferences for certain vehicle attributes while showing aversions to others, particularly in engine types and pricing. These insights are crucial for manufacturers and marketers aiming to align product offerings with consumer preferences.</p>
<p>To calculate the dollar value of having 3ft of cargo space compared to 2ft, we use the price coefficient as a conversion factor from utility units to dollars. The process involves translating the utility difference provided by the 3ft of cargo space into a monetary equivalent.</p>
<section id="given" class="level4">
<h4 class="anchored" data-anchor-id="given">Given:</h4>
<ul>
<li><strong>Utility Coefficient for 3ft of Cargo Space</strong>: ( _{} = 0.5387 )</li>
<li><strong>Price Coefficient (Per Thousand Dollars)</strong>: ( _{} = -0.0112 )</li>
</ul>
</section>
<section id="calculation" class="level4">
<h4 class="anchored" data-anchor-id="calculation">Calculation:</h4>
<p>The monetary value of the utility difference provided by 3ft of cargo space, as compared to 2ft, is calculated using the formula:</p>
<p>[ = ]</p>
</section>
<section id="result" class="level4">
<h4 class="anchored" data-anchor-id="result">Result:</h4>
<p>[ = ]</p>
<p>This calculation results in approximately $48.1 thousand. This value represents the additional amount, in thousands of dollars, that consumers are effectively willing to pay for an increase in cargo space from 2ft to 3ft, all else being constant.</p>
</section>
<section id="conclusion-1" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-1">Conclusion:</h4>
<p>The analysis shows that cargo space is a highly valued feature in vehicles, with a significant dollar amount associated with additional space. This insight can be crucial for vehicle manufacturers and marketers in positioning their products to align with consumer preferences.</p>
</section>
</section>
<section id="predict-the-market-shares-of-the-six-minivans" class="level3">
<h3 class="anchored" data-anchor-id="predict-the-market-shares-of-the-six-minivans">Predict the market shares of the six minivans</h3>
<table class="table">
<thead>
<tr class="header">
<th>Minivan</th>
<th>Seats</th>
<th>Cargo</th>
<th>Engine</th>
<th>Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>30</td>
</tr>
<tr class="even">
<td>B</td>
<td>6</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="odd">
<td>C</td>
<td>8</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="even">
<td>D</td>
<td>7</td>
<td>3</td>
<td>Gas</td>
<td>40</td>
</tr>
<tr class="odd">
<td>E</td>
<td>6</td>
<td>2</td>
<td>Elec</td>
<td>40</td>
</tr>
<tr class="even">
<td>F</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>35</td>
</tr>
</tbody>
</table>
<div id="565a71e3" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Attributes matrix for the minivans</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>minivans <span class="op">=</span> np.array([</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">30</span>],  <span class="co"># Minivan A: 7 seats, 2ft cargo, Hybrid, $30k</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">30</span>],  <span class="co"># Minivan B: 6 seats, 2ft cargo, Gas, $30k</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">30</span>],  <span class="co"># Minivan C: 8 seats, 2ft cargo, Gas, $30k</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">40</span>],  <span class="co"># Minivan D: 7 seats, 3ft cargo, Gas, $40k</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">40</span>],  <span class="co"># Minivan E: 6 seats, 2ft cargo, Electric, $40k</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">35</span>]   <span class="co"># Minivan F: 7 seats, 2ft cargo, Hybrid, $35k</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients array corresponding to Seat_7, Seat_8, Cargo_3ft, Eng_hyb, Eng_elec, and price</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>beta <span class="op">=</span> np.array([<span class="op">-</span><span class="fl">0.2968</span>, <span class="op">-</span><span class="fl">0.0780</span>, <span class="fl">0.5387</span>, <span class="op">-</span><span class="fl">0.5356</span>, <span class="op">-</span><span class="fl">1.1532</span>, <span class="op">-</span><span class="fl">0.0112</span>])</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate utilities for each minivan</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>utilities <span class="op">=</span> np.dot(minivans, beta)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate probabilities using the softmax function</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>exp_utilities <span class="op">=</span> np.exp(utilities)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>probabilities <span class="op">=</span> exp_utilities <span class="op">/</span> exp_utilities.<span class="bu">sum</span>()</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Market Shares for each Minivan:"</span>, probabilities)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Market Shares for each Minivan: [0.10376561 0.23853942 0.22064048 0.2716283  0.06731174 0.09811444]</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>